// <auto-generated />
using System;
using BE_Capstone_Project.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE_Capstone_Project.Migrations
{
    [DbContext(typeof(OtmsdbContext))]
    partial class OtmsdbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BookingDate")
                        .HasColumnType("datetime");

                    b.Property<byte?>("BookingStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("CertificateId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CertificateID");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<byte?>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("PaymentStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("RefundDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("TourScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("TourScheduleID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("PK__Booking__3214EC27666AD904");

                    b.HasIndex("TourScheduleId");

                    b.HasIndex("UserId");

                    b.ToTable("Booking", (string)null);
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.BookingCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<byte?>("CustomerType")
                        .HasMaxLength(20)
                        .HasColumnType("tinyint");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentityId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IdentityID");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__BookingC__3214EC271E35F1B3");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingCustomer", (string)null);
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.CancelCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("CancelStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<byte?>("MinDaysBeforeTrip")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("RefundPercent")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__CancelCo__3214EC275035C402");

                    b.ToTable("CancelCondition", (string)null);
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("ChatType")
                        .HasColumnType("tinyint");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    b.HasKey("Id")
                        .HasName("PK__Chat__3214EC27C2840407");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StaffId");

                    b.ToTable("Chat", (string)null);
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"));

                    b.Property<string>("AboutUsDescription1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutUsDescription2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutUsImageAlt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AboutUsImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AboutUsTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CountriesCoveredCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExperienceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExperienceText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<int?>("HappyTravelersCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("YearsExperienceCount")
                        .HasColumnType("int");

                    b.HasKey("CompanyID")
                        .HasName("PK__Company__4D913760");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("Delay")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Feature__3214EC27");

                    b.ToTable("Feature", (string)null);
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LocationName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id")
                        .HasName("PK__Location__3214EC271C940BCA");

                    b.ToTable("Location", (string)null);
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte?>("NewsStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedAuthor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("PK__News__3214EC27F261B932");

                    b.HasIndex("UserId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte?>("NotificationType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC278158AC28");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("ReviewStatus")
                        .HasColumnType("bit");

                    b.Property<byte?>("Stars")
                        .HasColumnType("tinyint");

                    b.Property<int>("TourId")
                        .HasColumnType("int")
                        .HasColumnName("TourID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("PK__Review__3214EC2742A083D7");

                    b.HasIndex("BookingId");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Role__3214EC27574568B1");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CancelConditionId")
                        .HasColumnType("int")
                        .HasColumnName("CancelConditionID");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<decimal?>("ChildDiscount")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Duration")
                        .HasColumnType("tinyint");

                    b.Property<int>("EndLocationId")
                        .HasColumnType("int")
                        .HasColumnName("EndLocationID");

                    b.Property<decimal?>("GroupDiscount")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<byte?>("GroupNumber")
                        .HasColumnType("tinyint");

                    b.Property<short?>("MaxSeats")
                        .HasColumnType("smallint");

                    b.Property<short?>("MinSeats")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("StartLocationId")
                        .HasColumnType("int")
                        .HasColumnName("StartLocationID");

                    b.Property<bool?>("TourStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__Tour__3214EC27922073D7");

                    b.HasIndex("CancelConditionId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EndLocationId");

                    b.HasIndex("StartLocationId");

                    b.ToTable("Tour", (string)null);
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.TourCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__TourCate__3214EC2742F6D3C1");

                    b.ToTable("TourCategory", (string)null);
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.TourImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TourId")
                        .HasColumnType("int")
                        .HasColumnName("TourID");

                    b.HasKey("Id")
                        .HasName("PK__TourImag__3214EC275B48A654");

                    b.HasIndex("TourId");

                    b.ToTable("TourImage", (string)null);
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.TourPriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ChildrenDiscount")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateOnly?>("EndPriceDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("GroupDiscount")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("GroupNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("StartPriceDate")
                        .HasColumnType("date");

                    b.Property<int>("TourId")
                        .HasColumnType("int")
                        .HasColumnName("TourID");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__TourPric__3214EC27E8D812A6");

                    b.HasIndex("TourId");

                    b.ToTable("TourPriceHistory", (string)null);
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.TourSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DepartureDate")
                        .HasColumnType("date");

                    b.Property<byte?>("ScheduleStatus")
                        .HasColumnType("tinyint");

                    b.Property<int>("TourId")
                        .HasColumnType("int")
                        .HasColumnName("TourID");

                    b.HasKey("Id")
                        .HasName("PK__TourSche__3214EC27D9098D1C");

                    b.HasIndex("TourId");

                    b.ToTable("TourSchedule", (string)null);
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PasswordResetExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<byte?>("UserStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__User__3214EC274AAAED85");

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TourId")
                        .HasColumnType("int")
                        .HasColumnName("TourID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("PK__Wishlist__3214EC2741A85014");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("Wishlist", (string)null);
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Booking", b =>
                {
                    b.HasOne("BE_Capstone_Project.Domain.Models.TourSchedule", "TourSchedule")
                        .WithMany("Bookings")
                        .HasForeignKey("TourScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK__Booking__TourSch__6477ECF3");

                    b.HasOne("BE_Capstone_Project.Domain.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Booking__UserID__6383C8BA");

                    b.Navigation("TourSchedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.BookingCustomer", b =>
                {
                    b.HasOne("BE_Capstone_Project.Domain.Models.Booking", "Booking")
                        .WithMany("BookingCustomers")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK__BookingCu__Booki__656C112C");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Chat", b =>
                {
                    b.HasOne("BE_Capstone_Project.Domain.Models.User", "Customer")
                        .WithMany("ChatCustomers")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__Chat__CustomerID__5812160E");

                    b.HasOne("BE_Capstone_Project.Domain.Models.User", "Staff")
                        .WithMany("ChatStaffs")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK__Chat__StaffID__571DF1D5");

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.News", b =>
                {
                    b.HasOne("BE_Capstone_Project.Domain.Models.User", "User")
                        .WithMany("News")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__News__UserID__5535A963");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Notification", b =>
                {
                    b.HasOne("BE_Capstone_Project.Domain.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__5629CD9C");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Review", b =>
                {
                    b.HasOne("BE_Capstone_Project.Domain.Models.Booking", "Booking")
                        .WithMany("Reviews")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK__Review__BookingI__5AEE82B9");

                    b.HasOne("BE_Capstone_Project.Domain.Models.Tour", "Tour")
                        .WithMany("Reviews")
                        .HasForeignKey("TourId")
                        .IsRequired()
                        .HasConstraintName("FK__Review__TourID__59FA5E80");

                    b.HasOne("BE_Capstone_Project.Domain.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Review__UserID__59063A47");

                    b.Navigation("Booking");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Tour", b =>
                {
                    b.HasOne("BE_Capstone_Project.Domain.Models.CancelCondition", "CancelCondition")
                        .WithMany("Tours")
                        .HasForeignKey("CancelConditionId")
                        .IsRequired()
                        .HasConstraintName("FK__Tour__CancelCond__60A75C0F");

                    b.HasOne("BE_Capstone_Project.Domain.Models.TourCategory", "Category")
                        .WithMany("Tours")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Tour__CategoryID__5FB337D6");

                    b.HasOne("BE_Capstone_Project.Domain.Models.Location", "EndLocation")
                        .WithMany("TourEndLocations")
                        .HasForeignKey("EndLocationId")
                        .IsRequired()
                        .HasConstraintName("FK__Tour__EndLocatio__5EBF139D");

                    b.HasOne("BE_Capstone_Project.Domain.Models.Location", "StartLocation")
                        .WithMany("TourStartLocations")
                        .HasForeignKey("StartLocationId")
                        .IsRequired()
                        .HasConstraintName("FK__Tour__StartLocat__5DCAEF64");

                    b.Navigation("CancelCondition");

                    b.Navigation("Category");

                    b.Navigation("EndLocation");

                    b.Navigation("StartLocation");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.TourImage", b =>
                {
                    b.HasOne("BE_Capstone_Project.Domain.Models.Tour", "Tour")
                        .WithMany("TourImages")
                        .HasForeignKey("TourId")
                        .IsRequired()
                        .HasConstraintName("FK__TourImage__TourI__619B8048");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.TourPriceHistory", b =>
                {
                    b.HasOne("BE_Capstone_Project.Domain.Models.Tour", "Tour")
                        .WithMany("TourPriceHistories")
                        .HasForeignKey("TourId")
                        .IsRequired()
                        .HasConstraintName("FK__TourPrice__TourI__66603565");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.TourSchedule", b =>
                {
                    b.HasOne("BE_Capstone_Project.Domain.Models.Tour", "Tour")
                        .WithMany("TourSchedules")
                        .HasForeignKey("TourId")
                        .IsRequired()
                        .HasConstraintName("FK__TourSched__TourI__628FA481");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.User", b =>
                {
                    b.HasOne("BE_Capstone_Project.Domain.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__User__RoleID__5441852A");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Wishlist", b =>
                {
                    b.HasOne("BE_Capstone_Project.Domain.Models.Tour", "Tour")
                        .WithMany("Wishlists")
                        .HasForeignKey("TourId")
                        .IsRequired()
                        .HasConstraintName("FK__Wishlist__TourID__5CD6CB2B");

                    b.HasOne("BE_Capstone_Project.Domain.Models.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Wishlist__UserID__5BE2A6F2");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Booking", b =>
                {
                    b.Navigation("BookingCustomers");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.CancelCondition", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Location", b =>
                {
                    b.Navigation("TourEndLocations");

                    b.Navigation("TourStartLocations");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.Tour", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("TourImages");

                    b.Navigation("TourPriceHistories");

                    b.Navigation("TourSchedules");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.TourCategory", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.TourSchedule", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BE_Capstone_Project.Domain.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ChatCustomers");

                    b.Navigation("ChatStaffs");

                    b.Navigation("News");

                    b.Navigation("Notifications");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
